CMS.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult AdminLeftNav()
        {
            return PartialView();
        }
	}
}

CMS.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CMS.WebUI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" class="app" ng-app="Cepefagel">
<head>
    <meta charset="utf-8" />
    <title>Notebook | Web Application</title>
    <meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/animate.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/font-awesome.min.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/app.css" type="text/css" />
    <!--[if lt IE 9]>
    <script src="~/Scripts/ie/html5shiv.js"></script>
    <script src="~/Scripts/ie/respond.min.js"></script>
    <script src="~/Scripts/ie/excanvas.js"></script>
    <![endif]-->
    <!--    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>-->
</head>
<body>
    <section class="vbox">
        <header class="bg-dark dk header navbar navbar-fixed-top-xs">
            <div class="navbar-header aside-md">
                <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
                    <i class="fa fa-bars"></i>
                </a>
                <a href="#" class="navbar-brand" data-toggle="fullscreen"><img src="~/images/logo.png" class="m-r-sm">Benamix</a>
                <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
                    <i class="fa fa-cog"></i>
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right hidden-xs nav-user">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="thumb-sm avatar pull-left">
                            <img src="/images/avatar.jpg">
                        </span>
                        Admin <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight">
                        <span class="arrow top"></span>

                    </ul>
                </li>
            </ul>
        </header>
        <section>
            <section class="hbox stretch">
                <aside class="bg-dark lter aside-md hidden-print" id="nav">
                    <section class="vbox">
                        @{Html.RenderAction("AdminLeftNav", "Nav");}                        
                        <footer class="footer lt hidden-xs b-t b-dark">
                            <div id="chat" class="dropup">
                                <section class="dropdown-menu on aside-md m-l-n">
                                    <section class="panel bg-white">
                                        <header class="panel-heading b-b b-light">Active chats</header>
                                        <div class="panel-body animated fadeInRight">
                                            <p class="text-sm">No active chats.</p>
                                            <p><a href="#" class="btn btn-sm btn-default">Start a chat</a></p>
                                        </div>
                                    </section>
                                </section>
                            </div>
                            <div id="invite" class="dropup">
                                <section class="dropdown-menu on aside-md m-l-n">
                                    <section class="panel bg-white">
                                        <header class="panel-heading b-b b-light">
                                            John <i class="fa fa-circle text-success"></i>
                                        </header>
                                        <div class="panel-body animated fadeInRight">
                                            <p class="text-sm">No contacts in your lists.</p>
                                            <p>
                                                <a href="#" class="btn btn-sm btn-facebook">
                                                    <i class="fa fa-fw fa-facebook"></i> Invite
                                                    from
                                                    Facebook
                                                </a>
                                            </p>
                                        </div>
                                    </section>
                                </section>
                            </div>
                            <a href="#nav" data-toggle="class:nav-xs" class="pull-right btn btn-sm btn-dark btn-icon">
                                <i class="fa fa-angle-left text"></i>
                                <i class="fa fa-angle-right text-active"></i>
                            </a>
                        </footer>
</section>
</aside>
                <section id="content">
                    @*Html.AdminCrumb(Request.Url.AbsolutePath)*@
                    @RenderBody()
                </section>
            </section>
        </section>
        </section>
        <script src="~/Scripts/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="~/Scripts/bootstrap.js"></script>
        <!-- App -->
        <script src="~/Scripts/app.js"></script>
        <script src="~/Scripts/app.plugin.js"></script>
        <script src="~/Scripts/jquery.slimscroll.min.js"></script>
        <script src="~/Scripts/jquery.sortable.js"></script>
        @RenderSection("scripts", required: false)
</body>
</html>