CMS.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebUI.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CMS.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.WebUI.Controllers
{
    public class NavController : Controller
    {
        //
        // GET: /Nav/
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult AdminLeftNav()
        {
            return PartialView();
        }
	}
}

CMS.WebUI/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Domain.Entities;
using CMS.Domain.Abstract;

namespace CMS.WebUI.Controllers
{
    public class PageController : Controller
    {
        private IPageRepository repository;

        public PageController(IPageRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index()
        {
            var result = repository.Pages.ToList();
            if (result.Count() == 0)
                result = new List<Page>();
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Page page, string action)
        {
            if (ModelState.IsValid)
            {
                if (!repository.Add(page))
                {
                    TempData["message"] = "Ссылка не уникальна. Введите другую ссылку.";
                    return View(page);
                }
                else
                    repository.Commit();

                if (action == "save")
                    return View ("Edit", page);

                return RedirectToAction("Index");

            }
            else
                return View(page);
        }

        public ActionResult Edit(int pageID)
        {
            return View(repository.GetbyID(pageID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Page page, string action)
        {
            if (ModelState.IsValid)
            {
                repository.Update(page);
                repository.Commit();

                if (action == "return")
                    return RedirectToAction("Index");
            }
            return View(page);
        }

        public ActionResult Delete(int pageID)
        {
            repository.Delete(pageID);
            repository.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Copy(int pageID)
        {
            repository.Copy(pageID);
            repository.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Publish(int pageID)
        {
            repository.ChangeStatus(pageID);
            repository.Commit();
            return RedirectToAction("Index");
        }

        public ActionResult Save()
        {
            return RedirectToAction("Index");
        }

    }
}

CMS.WebUI/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Domain.Abstract;
using CMS.Domain.Entities;

namespace CMS.WebUI.Controllers
{
    public class ServiceController : Controller
    {
        private IServiceRepository repository;

        public ServiceController(IServiceRepository repo)
        {
            repository = repo;
        }
        
        public ActionResult Index()
        {
            var result = repository.Services.ToList();
            if (result.Count() == 0)
                result = new List<Service>();
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Service service, string action)
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Service serivce, string action)
        {
            return View();
        }

        public ActionResult Copy()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Delete()
        {
            return RedirectToAction("Index");
        }

        public ActionResult ChangeStatus()
        {
            return RedirectToAction("Index");
        }

	}
}

CMS.WebUI/Views/Nav/AdminLeftNav.cshtml
<section class="w-f scrollable">
    <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="5px" data-color="#333333">

        <!-- nav -->
        <nav class="nav-primary hidden-xs">
            <ul class="nav">
                <li class="active">
                    <a href="@Url.Action("Index", "Admin")" class="active">
                        <i class="fa fa-dashboard icon">
                            <b class="bg-danger"></b>
                        </i>
                        <span>Главная</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Page")">
                        <i class="fa fa-columns icon">
                            <b class="bg-warning"></b>
                        </i>
                        <span class="pull-right">
                            <i class="fa fa-angle-down text"></i>
                            <i class="fa fa-angle-up text-active"></i>
                        </span>
                        <span>Страницы</span>
                    </a>

                    <ul class="nav lt">
                        <li>
                            <a href="@Url.Action("Index", "Page")">
                                <i class="fa fa-angle-right"></i>
                                <span>Показать все</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Page")">
                                <i class="fa fa-angle-right"></i>
                                <span>Создать новую страницу</span>
                            </a>
                        </li>
                        </ul>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Service")">
                        <i class="fa fa-flask icon">
                            <b class="bg-success"></b>
                        </i>
                        <span class="pull-right">
                            <i class="fa fa-angle-down text"></i>
                            <i class="fa fa-angle-up text-active"></i>
                        </span>
                        <span>Услуги</span>
                    </a>

                    <ul class="nav lt">
                        <li>
                            <a href="@Url.Action("Index", "Service")">
                                <i class="fa fa-angle-right"></i>
                                <span>Показать все</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Service")">
                                <i class="fa fa-angle-right"></i>
                                <span>Создать новую услугу</span>
                            </a>
                        </li>
                        </ul>
                </li>

                @*<li>
                        <a href="#uikit">
                            <i class="fa fa-flask icon">
                                <b class="bg-success"></b>
                            </i>
                            <span class="pull-right">
                                <i class="fa fa-angle-down text"></i>
                                <i class="fa fa-angle-up text-active"></i>
                            </span>
                            <span>UI kit</span>
                        </a>
                        <ul class="nav lt">
                            <li>
                                <a href="buttons.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Buttons</span>
                                </a>
                            </li>
                            <li>
                                <a href="icons.html">
                                    <b class="badge bg-info pull-right">369</b>
                                    <i class="fa fa-angle-right"></i>
                                    <span>Icons</span>
                                </a>
                            </li>
                            <li>
                                <a href="grid.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Grid</span>
                                </a>
                            </li>
                            <li>
                                <a href="widgets.html">
                                    <b class="badge  pull-right">8</b>
                                    <i class="fa fa-angle-right"></i>
                                    <span>Widgets</span>
                                </a>
                            </li>
                            <li>
                                <a href="components.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Components</span>
                                </a>
                            </li>
                            <li>
                                <a href="list.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>List group</span>
                                </a>
                            </li>
                            <li>
                                <a href="#table">
                                    <i class="fa fa-angle-down text"></i>
                                    <i class="fa fa-angle-up text-active"></i>
                                    <span>Table</span>
                                </a>
                                <ul class="nav bg">
                                    <li>
                                        <a href="table-static.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Table static</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="table-datatable.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Datatable</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="table-datagrid.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Datagrid</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#form">
                                    <i class="fa fa-angle-down text"></i>
                                    <i class="fa fa-angle-up text-active"></i>
                                    <span>Form</span>
                                </a>
                                <ul class="nav bg">
                                    <li>
                                        <a href="form-elements.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Form elements</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="form-validation.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Form validation</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="form-wizard.html">
                                            <i class="fa fa-angle-right"></i>
                                            <span>Form wizard</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="chart.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Chart</span>
                                </a>
                            </li>
                            <li>
                                <a href="fullcalendar.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Fullcalendar</span>
                                </a>
                            </li>
                            <li>
                                <a href="portlet.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Portlet</span>
                                </a>
                            </li>
                            <li>
                                <a href="timeline.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Timeline</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pages">
                            <i class="fa fa-file-text icon">
                                <b class="bg-primary"></b>
                            </i>
                            <span class="pull-right">
                                <i class="fa fa-angle-down text"></i>
                                <i class="fa fa-angle-up text-active"></i>
                            </span>
                            <span>Pages</span>
                        </a>
                        <ul class="nav lt">
                            <li>
                                <a href="gallery.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Gallery</span>
                                </a>
                            </li>
                            <li>
                                <a href="profile.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="invoice.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Invoice</span>
                                </a>
                            </li>
                            <li>
                                <a href="intro.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Intro</span>
                                </a>
                            </li>
                            <li>
                                <a href="master.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Master</span>
                                </a>
                            </li>
                            <li>
                                <a href="gmap.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Google Map</span>
                                </a>
                            </li>
                            <li>
                                <a href="jvectormap.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Vector Map</span>
                                </a>
                            </li>
                            <li>
                                <a href="signin.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Signin</span>
                                </a>
                            </li>
                            <li>
                                <a href="signup.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>Signup</span>
                                </a>
                            </li>
                            <li>
                                <a href="404.html">
                                    <i class="fa fa-angle-right"></i>
                                    <span>404</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="mail.html">
                            <b class="badge bg-danger pull-right">3</b>
                            <i class="fa fa-envelope-o icon">
                                <b class="bg-primary dker"></b>
                            </i>
                            <span>Message</span>
                        </a>
                    </li>
                    <li>
                        <a href="notebook.html">
                            <i class="fa fa-pencil icon">
                                <b class="bg-info"></b>
                            </i>
                            <span>Notes</span>
                        </a>
                    </li>*@
            </ul>
        </nav>
        <!-- / nav -->
    </div>
</section>